name: Sync dev to main

on:
  push:
    branches: [ main ]   # main 有更新就触发
  workflow_dispatch:      # 也可手动触发

permissions:
  contents: write         # 允许推送分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch branches
        run: |
          git fetch origin main
          git fetch origin dev || true

      - name: Create or update dev to match main
        run: |
          # 如果 dev 不存在，则从 main 创建
          if ! git ls-remote --exit-code --heads origin dev >/dev/null 2>&1; then
            echo "dev not found on remote. Creating from main..."
            git push origin origin/main:refs/heads/dev
          else
            echo "dev exists. Forcing it to match main..."
            # 等价于：让远端 dev 指针 = origin/main
            git push --force origin origin/main:refs/heads/dev
          fi
